In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
mail=pd.read_csv(r'C:/Users/tegae/Downloads/mail_data.csv')

In [18]:
mail['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [19]:
mail.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
mail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [12]:
y=mail['Category'].map({'ham':0,'spam':1}).values.ravel()

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
X=mail['Message']

In [24]:
tfdv=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)

In [25]:
X_token=tfdv.fit_transform(X)

In [16]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X_token, y, test_size=0.3, random_state=23)

In [27]:
from sklearn.linear_model import LogisticRegression

In [45]:
logmodel=LogisticRegression(max_iter=1000,class_weight='balanced')

In [46]:
results=logmodel.fit(X_train,y_train)

In [47]:
from sklearn.metrics import classification_report,confusion_matrix

In [48]:
y_pred=results.predict(X_test)

In [49]:
print('Matrix\n',confusion_matrix(y_test,y_pred))
print('Report\n',classification_report(y_test,y_pred))

Matrix
 [[1424   13]
 [  20  215]]
Report
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      1437
           1       0.94      0.91      0.93       235

    accuracy                           0.98      1672
   macro avg       0.96      0.95      0.96      1672
weighted avg       0.98      0.98      0.98      1672



In [37]:
from sklearn.neighbors import KNeighborsClassifier

In [38]:
knn=KNeighborsClassifier(n_neighbors=20)

In [39]:
answer=knn.fit(X_train,y_train)

In [40]:
predictions=answer.predict(X_test)

In [41]:
print('Matrix\n',confusion_matrix(y_test,predictions))
print('Report\n',classification_report(y_test,predictions))

Matrix
 [[1437    0]
 [ 235    0]]
Report
               precision    recall  f1-score   support

           0       0.86      1.00      0.92      1437
           1       0.00      0.00      0.00       235

    accuracy                           0.86      1672
   macro avg       0.43      0.50      0.46      1672
weighted avg       0.74      0.86      0.79      1672



C:\Users\tegae\anaconda3\envs\islpenv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\tegae\anaconda3\envs\islpenv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\tegae\anaconda3\envs\islpenv\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [44]:
predictions[12:25]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [50]:
 mail['Message'].nunique()

5157